#!/bin/bash

#===============================================================================
#
#          FILE:  test.sh
#
#         USAGE:  ./test.sh
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Joe Brockmeier, jzb@zonker.net
#       COMPANY:  Dissociated Press
#       VERSION:  1.0
#       CREATED:  05/25/2007 10:31:01 PM MDT
#      REVISION:  ---
#===============================================================================

{
clean()
{
   rm -rf dist.fsod ratios.fsod
}

genOccPlot()
{
    IN="$1".out
    OUT="$1".eps
    gnuplot -e "inputfile='$IN'; outputfile='$OUT';" occupancyErrAvg.plt
}
genRatPlot()
{
    IN1="$1".out
    OUT="$1".eps
    gnuplot -e "inputfile='$IN1'; outputfile='$OUT';" occupancyErrRat.plt
}
genOccStat()
{
    firstFile=$(ls -1v "$1"Opar* | head -1)
    rm -rf "$1"*statOcc*
    numFiles=$(ls -dq "$1"Opar* | wc -l)
    Rscript avrAndstdOcc.r "$firstFile" "$numFiles"
    statFile=$(ls "$1"*statOcc* | head -1)
    statFile=${statFile%.out}
    genOccPlot "$statFile"
}
    fileStruct=$1
    dirEnv=$(awk NR==1 "$fileStruct")	
    execType=$(awk NR==3 "$fileStruct")

    awk "NR>3" "$fileStruct" > ./dist.fsod

    cd ./../"$dirEnv"/
    ./../Util/infoLog
    cd ./../Util/
   
    while read line
    do
        dist=$line
	read line
        edges=$line
	read line
	listRatios=$line
       
        for edge in $edges
        do
	    pathShort="./../$dirEnv/$execType/$dist/$edge"
	    if [ "$execType" == "deft" ]
            then
		pathLong="$pathShort/outputs"
		genOccStat "$pathLong/"
		mv "$pathLong/"*.eps "$pathShort/"
	    else		
		for ratio in $listRatios
		do
		    pathLong="$pathShort/$ratio/outputs"
		    genOccStat "$pathLong/"
		    mv "$pathLong/"*.eps "$pathShort/$ratio/"
		    cp "$pathLong/"*statOcc*.out "$pathShort/" 
		done
		firstFile=$(ls -1v "$pathShort/"*statOcc* | head -1)
		rm -rf "$pathShort/"*statRat*
		numFiles=$(ls -dq "$pathShort/"*statOcc* | wc -l)
		echo "$listRatios" > ratios.fsod		
		Rscript avrAndstdRat.r "$firstFile" "$numFiles" "ratios.fsod"
		rm -rf "$pathShort/"*statOcc*
		statFile=$(ls "$pathShort/"*statRat* | head -1)
		statFile=${statFile%.out}
		genRatPlot "$statFile"
	   fi
	done
    done < "dist.fsod"
    clean
}
