#!/bin/bash
#===============================================================================
#
#          FILE:  ---
#
#         USAGE:  ---
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  ---
#       COMPANY:  ---
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

{
    IN="$1".out
    OUT="$1".gif
    mkdir figures
    gnuplot -e "inputfile='$IN'; outputfile='$OUT'" heatmapGIF.plt
    x=$(ls -1v ./figures/*.gif)
    convert -delay 10 $x -alpha remove -scale 780x720 ./"$1".gif
    rm -rf figures
}
