#!/bin/bash

#===============================================================================
#
#          FILE:  test.sh
#
#         USAGE:  ./test.sh
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Joe Brockmeier, jzb@zonker.net
#       COMPANY:  Dissociated Press
#       VERSION:  1.0
#       CREATED:  05/25/2007 10:31:01 PM MDT
#      REVISION:  ---
#===============================================================================
{
    fileStruct=$1
    dirEnv=$(awk NR==1 "$fileStruct")
    execType=$(awk NR==3 "$fileStruct")
    
    awk "NR>3" "$fileStruct" > dist.fsod 
    
    cd ./../"$dirEnv"/
    ./../Util/infoLog
    cd ./../Util/

    while read line
    do
        dist=$line
	read line
        edges=$line
	read line
        pathShort="./../$dirEnv/$execType"      
	for edge in $edges
	do
            pathLong="$pathShort/$dist/$edge"		
	    if [ "$execType" == "deft" ]
	    then
		#CHAMMAAAA
	    else	        
	        listRatios=$(sed -n "/$dist/{n;n;p}" "$pathShort/$dirEnv"_"$execType.fsod" )
	        for ratio in $listRatios
	        do
		    #CHAMMAAAAAAA
		done
	    fi
        done
    done < "dist.fsod"    
}
